name: boitex_info_app

description: "The official Boitex Info app."

publish_to: 'none'

version: 1.6.1+6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.31.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.4
  firebase_storage: ^11.5.4
  firebase_messaging: ^14.9.2
  animated_gradient: ^0.0.3
  flutter_local_notifications: ^17.0.0
  timeline_tile: ^2.0.0
  cloud_functions: ^4.7.1
  flutter_secure_storage: ^9.0.0


  # Other packages
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  mobile_scanner: ^7.1.3
  signature: ^6.3.0
  share_plus: ^8.0.0
  printing: ^5.11.1
  pdf: ^3.10.8
  flutter_pdfview: ^1.3.2
  http: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.1  # âœ… ADDED FOR PDF SAVING
  google_fonts: ^4.0.3
  home_widget: ^0.5.0
  emoji_picker_flutter: ^2.2.0
  video_thumbnail: ^0.5.3
  animations: ^2.1.0
  csv: ^5.1.1
  file_saver: ^0.2.12
  connectivity_plus: ^6.0.5
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.3
  uuid: ^4.4.0
  gal: ^2.3.0
  fl_chart: ^0.68.0
  universal_html: ^2.2.4
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.2.0

  # For iOS style icons
  cupertino_icons: ^1.0.2
  photo_view: ^0.15.0
  video_player: ^2.10.0
  chewie: ^1.13.0
  timeago: ^3.7.1
  crypto: ^3.0.7
  path: ^1.9.1
  record: ^6.0.0
  just_audio: ^0.9.44
  audio_waveforms: ^2.0.1
  permission_handler: ^12.0.1
  app_links: ^6.4.1
  package_info_plus: ^9.0.0
  dio: ^5.9.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/boitex_logo.png
    - assets/images/logo.png
    - assets/images/cachet.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.jpg"
